import gradio as gr
import pickle
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import PowerTransformer

# ==========================
# Custom Preprocessor
# ==========================

class CustomPreprocessor(BaseEstimator, TransformerMixin):
    def __init__(self, numerical_features_transform, method='yeo-johnson'):
        self.numerical_features_transform = numerical_features_transform
        self.method = method
        self.transformers = {}
        self.columns_ = None

    def fit(self, X, y=None):
        self.columns_ = X.columns

        for col in self.numerical_features_transform:
            if col in X.columns:
                pt = PowerTransformer(method=self.method)
                pt.fit(X[[col]])
                self.transformers[col] = pt

        return self

    def transform(self, X):
        X_transformed = X.copy()

        for col in self.numerical_features_transform:
            if col in X.columns and col in self.transformers:
                X_transformed[col] = self.transformers[col].transform(X[[col]])

        return X_transformed


# ==========================
# Load Model
# ==========================

Pipe = pickle.load(
    open('decision_tree_crop_recommender_pipeline.pkl', 'rb')
)

df = pickle.load(
    open('df.pkl', 'rb')
)

le = LabelEncoder()
le.fit(df['label'])

# ==========================
# Prediction Function
# ==========================

def get_output(N,P,K,temperature,humidity,ph,rainfall):

    test_df = pd.DataFrame({
        'N':[N],
        'P':[P],
        'K':[K],
        'temperature':[temperature],
        'humidity':[humidity],
        'ph':[ph],
        'rainfall':[rainfall]
    })

    output = Pipe.predict(test_df)[0]
    crop = le.inverse_transform([output])[0]

    return f"""
    <div class="result-card">

        <div class="crop-name">
            🌱 {crop.upper()}
        </div>

        <div class="result-description">
            Based on the provided soil and climate conditions,
            <span style="color:#22c55e;font-weight:bold;">
                {crop}
            </span>
            appears to be the most suitable crop.
        </div>

        <div class="result-list">
            ✅ Soil nutrients analyzed<br>
            ✅ Climate conditions checked<br>
            ✅ Recommendation generated by ML model
        </div>

    </div>
    """


# ==========================
# UI
# ==========================
custom_css = """
.gradio-container{
    max-width:1100px !important;
    margin:auto !important;
}

/* Center logo */
#logo-container{
    display:flex;
    justify-content:center;
    margin-top:20px;
    margin-bottom:10px;
}

/* Center markdown title */
.center-title{
    text-align:center;
    margin-bottom:20px;
}
"""

with gr.Blocks(
    css=custom_css,
    theme=gr.themes.Soft()
) as demo:
    
  with gr.Column():
    gr.Image(
        value="farmer.png",
        show_label=False,
        height=200,
        width=380
    )

    # Title
    gr.Markdown(
        """
        # 🌾 Smart Crop Recommendation System

        Enter your soil nutrient levels and environmental conditions.
        The machine learning model will recommend the most suitable crop.
        """
    )

    with gr.Row():
        N = gr.Slider(
            minimum=df['N'].min(),
            maximum=df['N'].max(),
            value=90,
            label="Nitrogen"
        )

        P = gr.Slider(
            minimum=df['P'].min(),
            maximum=df['P'].max(),
            value=42,
            label="Phosphorus"
        )

        K = gr.Slider(
            minimum=df['K'].min(),
            maximum=df['K'].max(),
            value=43,
            label="Potassium"
        )

    with gr.Row():
        temperature = gr.Slider(
            minimum=df['temperature'].min(),
            maximum=df['temperature'].max(),
            value=23.5,
            label="Temperature (°C)"
        )

        humidity = gr.Slider(
            minimum=df['humidity'].min(),
            maximum=df['humidity'].max(),
            value=82,
            label="Humidity (%)"
        )

    with gr.Row():
        ph = gr.Slider(
            minimum=df['ph'].min(),
            maximum=df['ph'].max(),
            value=6.5,
            label="Soil pH"
        )

        rainfall = gr.Slider(
            minimum=df['rainfall'].min(),
            maximum=df['rainfall'].max(),
            value=230,
            label="Rainfall (mm)"
        )

    predict_btn = gr.Button(
        "🔍 Recommend Crop",
        variant="primary"
    )

    output = gr.HTML()

    predict_btn.click(
        fn=get_output,
        inputs=[
            N,
            P,
            K,
            temperature,
            humidity,
            ph,
            rainfall
        ],
        outputs=output
    )

    gr.Examples(
        examples=[
            [90,42,43,23.5,82,6.5,230],
            [20,60,20,27,65,6.2,80],
            [40,70,80,30,60,6.8,100]
        ],
        inputs=[
            N,
            P,
            K,
            temperature,
            humidity,
            ph,
            rainfall
        ]
    )

demo.launch(share=True)